<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW0834" ignored="0" name="CalculatorTests" tests="19" failures="7" timestamp="09 Jan 2018 10:14:59 GMT" time="0.042" errors="0">
  <testcase name="expectedException" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="cot" time="0.001" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="division" time="0.001" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="divisionNegative" time="0.001" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [-2]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [-2]at com.epam.tam.demo.CalculatorTest.divisionNegative(CalculatorTest.java:35)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- divisionNegative -->
  <testcase name="multiplication" time="0.001" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="cos1" time="0.002" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [0.707107] but found [0.8509035245341184]">
      <![CDATA[java.lang.AssertionError: expected [0.707107] but found [0.8509035245341184]at com.epam.tam.demo.CalculatorTest.cos1(CalculatorTest.java:97)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cos1 -->
  <testcase name="negativeNumber" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="negativeNumberNegative" time="0.0" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at com.epam.tam.demo.CalculatorTest.negativeNumberNegative(CalculatorTest.java:84)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- negativeNumberNegative -->
  <testcase name="postiveNumber" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="postiveNumberNegative" time="0.001" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at com.epam.tam.demo.CalculatorTest.postiveNumberNegative(CalculatorTest.java:75)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- postiveNumberNegative -->
  <testcase name="power" time="0.001" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="powerNegative1" time="0.001" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [8.0] but found [0.125]">
      <![CDATA[java.lang.AssertionError: expected [8.0] but found [0.125]at com.epam.tam.demo.CalculatorTest.powerNegative1(CalculatorTest.java:59)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- powerNegative1 -->
  <testcase name="sumNegative" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="sin1" time="0.0" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [0.707107] but found [0.8509035245341184]">
      <![CDATA[java.lang.AssertionError: expected [0.707107] but found [0.8509035245341184]at com.epam.tam.demo.CalculatorTest.sin1(CalculatorTest.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- sin1 -->
  <testcase name="powerNegative2" time="0.001" classname="com.epam.tam.demo.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [8.0] but found [-8.0]">
      <![CDATA[java.lang.AssertionError: expected [8.0] but found [-8.0]at com.epam.tam.demo.CalculatorTest.powerNegative2(CalculatorTest.java:65)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- powerNegative2 -->
  <testcase name="tan" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="sum" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="sumOfNumbers" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
  <testcase name="sumOfNumbers" time="0.0" classname="com.epam.tam.demo.CalculatorTest"/>
</testsuite> <!-- CalculatorTests -->
